const { ChartJSNodeCanvas } = require("chartjs-node-canvas");
const path = require("path");
const fs = require("fs");
const express = require("express");
const router = express.Router();
const jwt = require("jsonwebtoken");
const bcrypt = require("bcrypt");
const Admin = require("../models/Admin");

const SECRET_KEY = process.env.JWT_SECRET;
const Patient = require("../models/Patient");

// Admin Login
router.post("/login", async (req, res) => {
  try {
    const { username, password } = req.body;

    console.log("Entered username:", username);
    console.log("Entered password:", password);

    const admin = await Admin.findOne({ username });

    console.log("Admin found:", admin);

    if (!admin) {
      return res.status(400).json({ message: "Invalid credentials" });
    }

    const isMatch = await bcrypt.compare(password, admin.password);

    console.log("Password match:", isMatch);

    if (!isMatch) {
      return res.status(400).json({ message: "Invalid credentials" });
    }

    // ✅ SUCCESS CASE (THIS MUST RUN)
    const token = jwt.sign(
      { id: admin._id, role: admin.role },
      process.env.JWT_SECRET || "jaydev_secret_key",
      { expiresIn: "1h" }
    );

    res.cookie("token", token, {
      httpOnly: true,
      secure: true,
      sameSite: "none"
    });

    return res.json({ message: "Login successful" }); // 🔥 IMPORTANT

  } catch (error) {
    console.error(error);
    return res.status(500).json({ message: "Internal server error" });
  }
});

router.get("/analytics/download", async (req, res) => {
  try {
    const patients = await Patient.find();

    const width = 800;
    const height = 400;
    const chartJSNodeCanvas = new ChartJSNodeCanvas({ width, height });

    // ===== COUNT DEPARTMENT DATA =====
    const departmentCount = {};
    patients.forEach((p) => {
      const dept = p.department || "Unknown";
      departmentCount[dept] = (departmentCount[dept] || 0) + 1;
    });

    const configuration = {
      type: "bar",
      data: {
        labels: Object.keys(departmentCount),
        datasets: [
          {
            label: "Patients by Department",
            data: Object.values(departmentCount),
            backgroundColor: "#0077B6",
          },
        ],
      },
      options: {
        plugins: {
          legend: { display: false },
        },
      },
    };

    const chartImage = await chartJSNodeCanvas.renderToBuffer(configuration);

    const doc = new PDFDocument({ size: "A4", margin: 50 });

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=Analytics_Report.pdf"
    );
    res.setHeader("Content-Type", "application/pdf");

    doc.pipe(res);

    // ================= HEADER =================

    const logoPath = path.join(__dirname, "../assets/logo.png");

    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, 50, 40, { width: 60 });
    }

    doc
      .font("Helvetica-Bold")
      .fontSize(22)
      .fillColor("#0A2E5C")
      .text("Jaydev Hospital Analytics Report", 130, 50);

    doc
      .font("Helvetica")
      .fontSize(10)
      .fillColor("gray")
      .text(`Generated on: ${new Date().toLocaleString()}`, 130, 75);

    doc.moveTo(50, 110).lineTo(550, 110).stroke();

    doc.moveDown(4);

    // ================= SUMMARY =================

    const totalPatients = patients.length;

    let completed = 0;
    patients.forEach((p) => {
      p.appointments.forEach((a) => {
        if (a.status === "Completed") completed++;
      });
    });

    const revenue = completed * 500;
    const gst = revenue * 0.18;
    const totalRevenue = revenue + gst;

    doc
      .font("Helvetica-Bold")
      .fontSize(14)
      .fillColor("black")
      .text("Summary Overview");

    doc.moveDown(1);

    doc
      .font("Helvetica")
      .fontSize(12)
      .text(`Total Patients: ${totalPatients}`)
      .text(`Completed Appointments: ${completed}`)
      .text(`Revenue (Before GST): ₹${revenue}`)
      .text(`GST (18%): ₹${gst.toFixed(2)}`)
      .text(`Total Revenue: ₹${totalRevenue.toFixed(2)}`);

    // ================= CHART PAGE =================

    doc.addPage();

    doc
      .font("Helvetica-Bold")
      .fontSize(18)
      .text("Department Analytics Chart", { align: "center" });

    doc.moveDown(2);

    doc.image(chartImage, {
      fit: [500, 300],
      align: "center",
    });

    // ================= FOOTER =================

    doc
      .fontSize(9)
      .fillColor("gray")
      .text(
        "This report is generated by Jaydev Hospital ERP System.",
        50,
        770,
        { align: "center" }
      );

    doc.end();
  } catch (error) {
    console.error(error);
   console.error(error);
   res.status(500).json({ message: "Internal server error" });
  }
});
router.post("/logout", (req, res) => {
  res.clearCookie("token");
  res.json({ message: "Logged out" });
});

const verifyToken = require("../middleware/authMiddleware"); // 🔥 make sure this is at top

router.get("/check", verifyToken, (req, res) => {
  res.json({ message: "Authenticated" });
});
module.exports = router;